commandlinefu_id: 13684
translator:
  weibo: tgic
command: |-
  ifconfig | egrep -A2 "eth|wlan" | tr -d "\n"| sed 's/\-\-/\n/g'|awk '{print "mac: "$5 " " $7}' | sed 's/addr:/addr: /g'
summary: |-
  同时输出mac和ip
